### PR TITLE
remove bad character from json files

### PR DESCRIPTION
**Pull request by robatipoor**
some library problem with deserialize  json file because files contain bad character i fix all of them and add example how to load json in java

### CODE REVIEW

**Comment by VahidN** [comment]
Hmm.... what was that bad character? Because when I use .NET libraries there is no problem and actually I created these files with them.

**Comment by VahidN** [comment]
Ok. You just removed `EF BB BF` bytes from the beginning of the files. It's called `BOM` and it's used to mark the file as `UTF8`: https://en.wikipedia.org/wiki/Byte_order_mark
If you open and read these files as `UTF8`, there will be no problem:
 https://stackoverflow.com/a/13988345/298573
 https://www.rgagnon.com/javadetails/java-handle-utf8-file-with-bom.html

**Comment by robatipoor** [comment]
oh yes I did not know about it Thanks for the answer

**Comment by VahidN** [comment]
Please update your repo to revert `remove bad character from json files`. I will merge your Java code. Thanks.

**Comment by robatipoor** [comment]
Ok done

**Comment by VahidN** [comment]
Thank you.

**Pull request merged**
